---
- name: Backing up Arch...
  hosts: localhost
  roles:
    #Configurations
    - roles/backup/configurations/hyprland
    - roles/backup/configurations/noctalia
    - roles/backup/configurations/tmux
    - roles/backup/configurations/zsh
    - roles/backup/configurations/vim
    - roles/backup/configurations/misc
    - roles/backup/configurations/btrfs-backup
    #Applications
    - roles/backup/applications/zed
    - roles/backup/applications/wireshark
    #Arch Build
    #- roles/backup/arch-build
