#SPDX-License-Identifier: MIT-0
---
# tasks fill
- name: Configuring noctalia...
  become: true
  become_user: "{{target_user}}"
  become_method: su
  file:
    path: "{{target_home_dir}}/.config/noctalia/"
    state: directory

- name:
  become: true
  become_user: "{{target_user}}"
  become_method: su
  copy:
    src: "{{target_home_dir}}/arch-build/roles/setup/configurations/noctalia/files/noctalia-config.toml"
    dest: "{{target_home_dir}}/.config/noctalia/"

- name:
  become: true
  become_user: "{{target_user}}"
  become_method: su
  file:
    path: "{{target_home_dir}}/Pictures/Wallpapers"
    state: directory

- name:
  become: true
  become_user: "{{target_user}}"
  become_method: su
  copy:
    src: "{{target_home_dir}}/arch-build/roles/setup/configurations/noctalia/files/wallpaper.jpg"
    dest: "{{target_home_dir}}/Pictures/Wallpapers/"
