#SPDX-License-Identifier: MIT-0
---
# tasks file for hyprland
- name: Backing up hyprland...
  become: true
  become_user: "{{target_user}}"
  become_method: su
  copy:
    src: "{{target_home_dir}}/.config/hyprland/hyprland.lua"
    dest: "{{target_home_dir}}/arch-build/roles/setup/configurations/hyprland/files/hyprland.lua"

- name:
  become: true
  become_user: "{{target_user}}"
  become_method: su
  copy:
    src: "{{target_home_dir}}/.config/hyprland/modules/keybindings.lua"
    dest: "{{target_home_dir}}/arch-build/roles/setup/configurations/hyprland/files/modules/keybindings.lua"
