---
PACKAGES:
  [
    "go",
    "zsh",
    "vim",
    "tmux",
    "tree",
    "foot",
    "btop",
    "kalk",
    "grim",
    "slurp",
    "satty",
    "xclip",
    "gparted",
    "flatpak",
    "noctalia",
    "base-devel",
    "wl-clipboard",
    "plasma-integration",
    "ttf-jetbrains-mono",
    "zsh-autosuggestions",
  ]
