---
PACKAGES:
  [
    "go",
    "gum",
    "zsh",
    "vim",
    "tmux",
    "tree",
    "foot",
    "btop",
    "kalk",
    "grim",
    "slurp",
    "satty",
    "xclip",
    "gparted",
    "flatpak",
    "ntfs-3g",
    "noctalia",
    "filelight",
    "os-prober",
    "xorg-xhost",
    "base-devel",
    "wl-clipboard",
    "plasma-integration",
    "ttf-jetbrains-mono",
    "zsh-autosuggestions",
  ]
