---
PACKAGES:
  [
    "zsh",
    "vim",
    "tmux",
    "tree",
    "foot",
    "btop",
    "kalk",
    "xclip",
    "gparted",
    "flatpak",
    "noctalia",
    "base-devel",
    "plasma-integration",
    "ttf-jetbrains-mono",
    "zsh-autosuggestions",
  ]
