#SPDX-License-Identifier: MIT-0
---
# tasks file for misc
# Foot (Terminal)
- name:
  become: true
  become_user: "{{target_user}}"
  become_method: su
  file:
    path: "{{target_home_dir}}/.config/foot/"
    state: directory

- name:
  become: true
  become_user: "{{target_user}}"
  become_method: su
  copy:
    src: "{{target_home_dir}}/arch-build/roles/setup/configurations/misc/files/foot.ini"
    dest: "{{target_home_dir}}/.config/foot/foot.ini"

# Dolphin
- name:
  become: true
  become_method: su
  copy:
    src: "{{ target_home_dir }}/arch-build/roles/setup/configurations/misc/files/{{ item }}"
    dest: "{{ target_home_dir }}/.config/"
  loop:
    - kdeglobals
    - dolphinrc
